---
- hosts: routers
  gather_facts: False
  connection: network_cli
  become_method: enable

  tasks:
    - name: OSPF configuration for R1
      when: ansible_host == "10.2.0.1"
      ios_config:
        parents: router ospf 100
        lines:
          - router-id 10.2.0.0
          - network 10.2.0.0 0.0.0.3 area 0
          - network 10.2.2.0 0.0.0.3 area 0
          - network 192.168.1.0 0.0.0.255 area 0
          - passive-interface FastEthernet0/0

    - name: OSPF configuration for R2
      when: ansible_host == "10.2.1.1"
      ios_config:
        parents: router ospf 100
        lines:
          - router-id 10.2.1.0
          - network 10.2.1.0 0.0.0.3 area 0
          - network 10.2.0.0 0.0.0.3 area 0
          - network 192.168.2.0 0.0.0.255 area 0
          - passive-interface FastEthernet0/0
          - default-information originate

    - name: OSPF configuration for R3
      when: ansible_host == "10.2.1.2"
      ios_config:
        parents: router ospf 100
        lines:
          - router-id 10.2.2.0
          - network 10.2.1.0 0.0.0.3 area 0
          - network 10.2.2.0 0.0.0.3 area 0
          - network 192.168.3.0 0.0.0.255 area 0
          - passive-interface FastEthernet0/0
